site_name: Modern Leadership Toolbox
site_url: https://plle.github.io/leadership/
repo_url: https://github.com/PLLE/leadership
repo_name: plle/leadership
edit_uri: edit/main/docs/
theme:
  name: material
  icon:
    repo: fontawesome/brands/git
    edit: material/pencil 
    view: material/eye
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    #- toc.integrate
    - toc.follow
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
  custom_dir: overrides

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # Mermaid import
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

copyright: |
  &copy; 2023 <a href="https://github.com/plle"  target="_blank" rel="noopener">Paul Liepe</a>

